apiVersion: v1
kind: Pod
metadata:
  name: nginx-multi-container
spec:
  containers:
    - name: nginx-container-1
      image: nginx
      ports:
        - containerPort: 8081
    - name: nginx-container-2
      image: nginx
      ports:
        - containerPort: 8082
